/*
 * Java domain class for entity "Companys" 
 * Created on 2026-02-04 ( 06:20:02 )
 * Generated by Telosys embedded generator ( version 4.3.0 )
 */

package gendev.it.serenity.users.infrastructure.entity;

import java.io.Serializable;

/**
 * Domain class for entity "Companys"
 *
 * @author Telosys
 *
 */
public class Companys implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY ATTRIBUTES 
    private String     myfield ;

    /**
     * Constructor
     */
    public Companys() {
		super();
    }

     //--- GETTERS & SETTERS FOR ATTRIBUTES
    public void setMyfield( String myfield ) {
        this.myfield = myfield ;
    }
    public String getMyfield() {
        return this.myfield;
    }


	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Companys[");
		sb.append("myfield=").append(myfield);
		sb.append("]");
		return sb.toString();
	}
}
