/*
 * JUnit test case for bean Companys
 * Created on 2026-02-04 ( 06:20:02 )
 * Generated by Telosys embedded generator ( version 4.3.0 )
 */
package gendev.it.serenity.users.infrastructure.entity;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

/**
 * JUnit test case for bean Companys
 * 
 * @author Telosys
 *
 */
class CompanysTest {

	@Test
	void testSettersAndGetters() {
		
		Companys companys = new Companys();


		//--- Test setter/getter for attribute "myfield"  ( type : String )
		companys.setMyfield( "A" ) ;
		assertEquals( "A", companys.getMyfield() ) ;

	}
}
