\c serenity
GRANT USAGE, CREATE ON SCHEMA public TO serenity;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO serenity;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO serenity;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO serenity;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO serenity;
